import type { Alert } from "@/types";

export function mockAlerts(): Alert[] {
  return [
    {
      id: "al1",
      severity: "critical",
      module: "vendas",
      message: "Margem média hoje caiu para 42%",
      detail: "Abaixo do mínimo definido de 50%. Verificar descontos aplicados.",
      action_url: "/descontos",
      created_at: new Date().toISOString(),
      is_read: false,
    },
    {
      id: "al2",
      severity: "critical",
      module: "operacao",
      message: "2 encomendas prontas para entrega há mais de 15 dias",
      detail: "Sofia Carvalho (há 18 dias) e Ana Rodrigues (há 20 dias).",
      action_url: "/operacao",
      created_at: new Date().toISOString(),
      is_read: false,
    },
    {
      id: "al3",
      severity: "warning",
      module: "operacao",
      message: "Encomenda de Miguel Oliveira em atraso",
      detail: "Estava prevista há 2 dias. Em produção há 12 dias.",
      action_url: "/pipeline",
      created_at: new Date().toISOString(),
      is_read: false,
    },
    {
      id: "al4",
      severity: "warning",
      module: "stock",
      message: "5 armações sem venda há mais de 180 dias",
      detail: "Capital empatado: ~€2.100. Ray-Ban RB3025, Oakley OX8046, Tom Ford FT0248...",
      action_url: "/stock",
      created_at: new Date().toISOString(),
      is_read: false,
    },
    {
      id: "al5",
      severity: "warning",
      module: "pipeline",
      message: "3 orçamentos pendentes há mais de 3 dias",
      detail: "Rui Santos (€390), Catarina Lima (€870), outros.",
      action_url: "/pipeline",
      created_at: new Date().toISOString(),
      is_read: true,
    },
    {
      id: "al6",
      severity: "info",
      module: "clientes",
      message: "8 clientes com aniversário este mês",
      detail: "Oportunidade de campanha personalizada.",
      action_url: "/clientes",
      created_at: new Date().toISOString(),
      is_read: true,
    },
    {
      id: "al7",
      severity: "warning",
      module: "clientes",
      message: "3 clientes com lentes de contacto a acabar em 2 semanas",
      detail: "Sofia Carvalho, Catarina Lima, Luísa Pinto.",
      action_url: "/clientes",
      created_at: new Date().toISOString(),
      is_read: false,
    },
    {
      id: "al8",
      severity: "info",
      module: "vendas",
      message: "Cumprimento do objetivo mensal: 77%",
      detail: "42.300€ de 55.000€. Faltam 12.700€.",
      action_url: "/mes",
      created_at: new Date().toISOString(),
      is_read: true,
    },
  ];
}
